version: '3'
services:
  db:
    container_name: sign_gress_db
    hostname: db
    image: postgres:12
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'

  server:
    container_name: sign_gress_server
    hostname: server
    build:
      context: .
      network: host
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db

  adminer:
    container_name: sign_gress_adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  dbdata: null
