name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  pytest:
    name: pytest_on_github_actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.9

      - name: Setup environments
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.CRED_JSON_BASE64 }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > cred.json

      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          some_other_variable: foobar
          directory: .
          file_name: .env
          fail_on_empty: false
          envkey_POSTGRES_USER: postgres
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_HOST: localhost
          envkey_POSTGRES_DB: sign_gress_test

      - name: Up postgres docker container
        run: docker-compose up -d db

      - name: Run tests
        run: pipenv run pytest
